[package]
name = "mdspec"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Alexandrov <alexander.s.alexandrov@gmail.com>"]

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
glob = "0.3.1"
pulldown-cmark = "0.11"
pulldown-cmark-to-cmark = "13.0.0"
thiserror = "1.0.61"